// <auto-generated />
using System;
using FHussien_DatabaseSolution.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FHussien_DatabaseSolution.Migrations
{
    [DbContext(typeof(FHussienDatabaseContext))]
    partial class FHussienDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FHussien_DatabaseSolution.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Location 1",
                            Name = "Company 1"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Location 2",
                            Name = "Company 2"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Location 3",
                            Name = "Company 3"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Location 4",
                            Name = "Company 4"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Location 5",
                            Name = "Company 5"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Location 6",
                            Name = "Company 6"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Location 7",
                            Name = "Company 7"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Location 8",
                            Name = "Company 8"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Location 9",
                            Name = "Company 9"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Location 10",
                            Name = "Company 10"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Location 11",
                            Name = "Company 11"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Location 12",
                            Name = "Company 12"
                        },
                        new
                        {
                            Id = 13,
                            Location = "Location 13",
                            Name = "Company 13"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Location 14",
                            Name = "Company 14"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Location 15",
                            Name = "Company 15"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Location 16",
                            Name = "Company 16"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Location 17",
                            Name = "Company 17"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Location 18",
                            Name = "Company 18"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Location 19",
                            Name = "Company 19"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Location 20",
                            Name = "Company 20"
                        },
                        new
                        {
                            Id = 21,
                            Location = "Location 21",
                            Name = "Company 21"
                        },
                        new
                        {
                            Id = 22,
                            Location = "Location 22",
                            Name = "Company 22"
                        },
                        new
                        {
                            Id = 23,
                            Location = "Location 23",
                            Name = "Company 23"
                        },
                        new
                        {
                            Id = 24,
                            Location = "Location 24",
                            Name = "Company 24"
                        },
                        new
                        {
                            Id = 25,
                            Location = "Location 25",
                            Name = "Company 25"
                        },
                        new
                        {
                            Id = 26,
                            Location = "Location 26",
                            Name = "Company 26"
                        },
                        new
                        {
                            Id = 27,
                            Location = "Location 27",
                            Name = "Company 27"
                        },
                        new
                        {
                            Id = 28,
                            Location = "Location 28",
                            Name = "Company 28"
                        },
                        new
                        {
                            Id = 29,
                            Location = "Location 29",
                            Name = "Company 29"
                        },
                        new
                        {
                            Id = 30,
                            Location = "Location 30",
                            Name = "Company 30"
                        },
                        new
                        {
                            Id = 31,
                            Location = "Location 31",
                            Name = "Company 31"
                        },
                        new
                        {
                            Id = 32,
                            Location = "Location 32",
                            Name = "Company 32"
                        },
                        new
                        {
                            Id = 33,
                            Location = "Location 33",
                            Name = "Company 33"
                        },
                        new
                        {
                            Id = 34,
                            Location = "Location 34",
                            Name = "Company 34"
                        },
                        new
                        {
                            Id = 35,
                            Location = "Location 35",
                            Name = "Company 35"
                        },
                        new
                        {
                            Id = 36,
                            Location = "Location 36",
                            Name = "Company 36"
                        },
                        new
                        {
                            Id = 37,
                            Location = "Location 37",
                            Name = "Company 37"
                        },
                        new
                        {
                            Id = 38,
                            Location = "Location 38",
                            Name = "Company 38"
                        },
                        new
                        {
                            Id = 39,
                            Location = "Location 39",
                            Name = "Company 39"
                        },
                        new
                        {
                            Id = 40,
                            Location = "Location 40",
                            Name = "Company 40"
                        },
                        new
                        {
                            Id = 41,
                            Location = "Location 41",
                            Name = "Company 41"
                        },
                        new
                        {
                            Id = 42,
                            Location = "Location 42",
                            Name = "Company 42"
                        },
                        new
                        {
                            Id = 43,
                            Location = "Location 43",
                            Name = "Company 43"
                        },
                        new
                        {
                            Id = 44,
                            Location = "Location 44",
                            Name = "Company 44"
                        },
                        new
                        {
                            Id = 45,
                            Location = "Location 45",
                            Name = "Company 45"
                        },
                        new
                        {
                            Id = 46,
                            Location = "Location 46",
                            Name = "Company 46"
                        },
                        new
                        {
                            Id = 47,
                            Location = "Location 47",
                            Name = "Company 47"
                        },
                        new
                        {
                            Id = 48,
                            Location = "Location 48",
                            Name = "Company 48"
                        },
                        new
                        {
                            Id = 49,
                            Location = "Location 49",
                            Name = "Company 49"
                        },
                        new
                        {
                            Id = 50,
                            Location = "Location 50",
                            Name = "Company 50"
                        },
                        new
                        {
                            Id = 51,
                            Location = "Location 51",
                            Name = "Company 51"
                        },
                        new
                        {
                            Id = 52,
                            Location = "Location 52",
                            Name = "Company 52"
                        },
                        new
                        {
                            Id = 53,
                            Location = "Location 53",
                            Name = "Company 53"
                        },
                        new
                        {
                            Id = 54,
                            Location = "Location 54",
                            Name = "Company 54"
                        },
                        new
                        {
                            Id = 55,
                            Location = "Location 55",
                            Name = "Company 55"
                        },
                        new
                        {
                            Id = 56,
                            Location = "Location 56",
                            Name = "Company 56"
                        },
                        new
                        {
                            Id = 57,
                            Location = "Location 57",
                            Name = "Company 57"
                        },
                        new
                        {
                            Id = 58,
                            Location = "Location 58",
                            Name = "Company 58"
                        },
                        new
                        {
                            Id = 59,
                            Location = "Location 59",
                            Name = "Company 59"
                        },
                        new
                        {
                            Id = 60,
                            Location = "Location 60",
                            Name = "Company 60"
                        },
                        new
                        {
                            Id = 61,
                            Location = "Location 61",
                            Name = "Company 61"
                        },
                        new
                        {
                            Id = 62,
                            Location = "Location 62",
                            Name = "Company 62"
                        },
                        new
                        {
                            Id = 63,
                            Location = "Location 63",
                            Name = "Company 63"
                        },
                        new
                        {
                            Id = 64,
                            Location = "Location 64",
                            Name = "Company 64"
                        },
                        new
                        {
                            Id = 65,
                            Location = "Location 65",
                            Name = "Company 65"
                        },
                        new
                        {
                            Id = 66,
                            Location = "Location 66",
                            Name = "Company 66"
                        },
                        new
                        {
                            Id = 67,
                            Location = "Location 67",
                            Name = "Company 67"
                        },
                        new
                        {
                            Id = 68,
                            Location = "Location 68",
                            Name = "Company 68"
                        },
                        new
                        {
                            Id = 69,
                            Location = "Location 69",
                            Name = "Company 69"
                        },
                        new
                        {
                            Id = 70,
                            Location = "Location 70",
                            Name = "Company 70"
                        },
                        new
                        {
                            Id = 71,
                            Location = "Location 71",
                            Name = "Company 71"
                        },
                        new
                        {
                            Id = 72,
                            Location = "Location 72",
                            Name = "Company 72"
                        },
                        new
                        {
                            Id = 73,
                            Location = "Location 73",
                            Name = "Company 73"
                        },
                        new
                        {
                            Id = 74,
                            Location = "Location 74",
                            Name = "Company 74"
                        },
                        new
                        {
                            Id = 75,
                            Location = "Location 75",
                            Name = "Company 75"
                        },
                        new
                        {
                            Id = 76,
                            Location = "Location 76",
                            Name = "Company 76"
                        },
                        new
                        {
                            Id = 77,
                            Location = "Location 77",
                            Name = "Company 77"
                        },
                        new
                        {
                            Id = 78,
                            Location = "Location 78",
                            Name = "Company 78"
                        },
                        new
                        {
                            Id = 79,
                            Location = "Location 79",
                            Name = "Company 79"
                        },
                        new
                        {
                            Id = 80,
                            Location = "Location 80",
                            Name = "Company 80"
                        },
                        new
                        {
                            Id = 81,
                            Location = "Location 81",
                            Name = "Company 81"
                        },
                        new
                        {
                            Id = 82,
                            Location = "Location 82",
                            Name = "Company 82"
                        },
                        new
                        {
                            Id = 83,
                            Location = "Location 83",
                            Name = "Company 83"
                        },
                        new
                        {
                            Id = 84,
                            Location = "Location 84",
                            Name = "Company 84"
                        },
                        new
                        {
                            Id = 85,
                            Location = "Location 85",
                            Name = "Company 85"
                        },
                        new
                        {
                            Id = 86,
                            Location = "Location 86",
                            Name = "Company 86"
                        },
                        new
                        {
                            Id = 87,
                            Location = "Location 87",
                            Name = "Company 87"
                        },
                        new
                        {
                            Id = 88,
                            Location = "Location 88",
                            Name = "Company 88"
                        },
                        new
                        {
                            Id = 89,
                            Location = "Location 89",
                            Name = "Company 89"
                        },
                        new
                        {
                            Id = 90,
                            Location = "Location 90",
                            Name = "Company 90"
                        },
                        new
                        {
                            Id = 91,
                            Location = "Location 91",
                            Name = "Company 91"
                        },
                        new
                        {
                            Id = 92,
                            Location = "Location 92",
                            Name = "Company 92"
                        },
                        new
                        {
                            Id = 93,
                            Location = "Location 93",
                            Name = "Company 93"
                        },
                        new
                        {
                            Id = 94,
                            Location = "Location 94",
                            Name = "Company 94"
                        },
                        new
                        {
                            Id = 95,
                            Location = "Location 95",
                            Name = "Company 95"
                        },
                        new
                        {
                            Id = 96,
                            Location = "Location 96",
                            Name = "Company 96"
                        },
                        new
                        {
                            Id = 97,
                            Location = "Location 97",
                            Name = "Company 97"
                        },
                        new
                        {
                            Id = 98,
                            Location = "Location 98",
                            Name = "Company 98"
                        },
                        new
                        {
                            Id = 99,
                            Location = "Location 99",
                            Name = "Company 99"
                        },
                        new
                        {
                            Id = 100,
                            Location = "Location 100",
                            Name = "Company 100"
                        });
                });

            modelBuilder.Entity("FHussien_DatabaseSolution.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Flat User",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("FHussien_DatabaseSolution.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserInformationId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserInformationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "admin.email1@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 1,
                            UserName = "Admin 1"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Email = "admin.email2@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 2,
                            UserName = "Admin 2"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Email = "admin.email3@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 3,
                            UserName = "Admin 3"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            Email = "admin.email4@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 4,
                            UserName = "Admin 4"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            Email = "admin.email5@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 5,
                            UserName = "Admin 5"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 6,
                            Email = "admin.email6@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 6,
                            UserName = "Admin 6"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 7,
                            Email = "admin.email7@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 7,
                            UserName = "Admin 7"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 8,
                            Email = "admin.email8@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 8,
                            UserName = "Admin 8"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 9,
                            Email = "admin.email9@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 9,
                            UserName = "Admin 9"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 10,
                            Email = "admin.email10@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 10,
                            UserName = "Admin 10"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 11,
                            Email = "admin.email11@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 11,
                            UserName = "Admin 11"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 12,
                            Email = "admin.email12@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 12,
                            UserName = "Admin 12"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 13,
                            Email = "admin.email13@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 13,
                            UserName = "Admin 13"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 14,
                            Email = "admin.email14@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 14,
                            UserName = "Admin 14"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 15,
                            Email = "admin.email15@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 15,
                            UserName = "Admin 15"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = 16,
                            Email = "admin.email16@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 16,
                            UserName = "Admin 16"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = 17,
                            Email = "admin.email17@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 17,
                            UserName = "Admin 17"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = 18,
                            Email = "admin.email18@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 18,
                            UserName = "Admin 18"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = 19,
                            Email = "admin.email19@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 19,
                            UserName = "Admin 19"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = 20,
                            Email = "admin.email20@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 20,
                            UserName = "Admin 20"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = 21,
                            Email = "admin.email21@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 21,
                            UserName = "Admin 21"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = 22,
                            Email = "admin.email22@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 22,
                            UserName = "Admin 22"
                        },
                        new
                        {
                            Id = 23,
                            CompanyId = 23,
                            Email = "admin.email23@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 23,
                            UserName = "Admin 23"
                        },
                        new
                        {
                            Id = 24,
                            CompanyId = 24,
                            Email = "admin.email24@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 24,
                            UserName = "Admin 24"
                        },
                        new
                        {
                            Id = 25,
                            CompanyId = 25,
                            Email = "admin.email25@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 25,
                            UserName = "Admin 25"
                        },
                        new
                        {
                            Id = 26,
                            CompanyId = 26,
                            Email = "admin.email26@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 26,
                            UserName = "Admin 26"
                        },
                        new
                        {
                            Id = 27,
                            CompanyId = 27,
                            Email = "admin.email27@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 27,
                            UserName = "Admin 27"
                        },
                        new
                        {
                            Id = 28,
                            CompanyId = 28,
                            Email = "admin.email28@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 28,
                            UserName = "Admin 28"
                        },
                        new
                        {
                            Id = 29,
                            CompanyId = 29,
                            Email = "admin.email29@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 29,
                            UserName = "Admin 29"
                        },
                        new
                        {
                            Id = 30,
                            CompanyId = 30,
                            Email = "admin.email30@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 30,
                            UserName = "Admin 30"
                        },
                        new
                        {
                            Id = 31,
                            CompanyId = 31,
                            Email = "admin.email31@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 31,
                            UserName = "Admin 31"
                        },
                        new
                        {
                            Id = 32,
                            CompanyId = 32,
                            Email = "admin.email32@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 32,
                            UserName = "Admin 32"
                        },
                        new
                        {
                            Id = 33,
                            CompanyId = 33,
                            Email = "admin.email33@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 33,
                            UserName = "Admin 33"
                        },
                        new
                        {
                            Id = 34,
                            CompanyId = 34,
                            Email = "admin.email34@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 34,
                            UserName = "Admin 34"
                        },
                        new
                        {
                            Id = 35,
                            CompanyId = 35,
                            Email = "admin.email35@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 35,
                            UserName = "Admin 35"
                        },
                        new
                        {
                            Id = 36,
                            CompanyId = 36,
                            Email = "admin.email36@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 36,
                            UserName = "Admin 36"
                        },
                        new
                        {
                            Id = 37,
                            CompanyId = 37,
                            Email = "admin.email37@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 37,
                            UserName = "Admin 37"
                        },
                        new
                        {
                            Id = 38,
                            CompanyId = 38,
                            Email = "admin.email38@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 38,
                            UserName = "Admin 38"
                        },
                        new
                        {
                            Id = 39,
                            CompanyId = 39,
                            Email = "admin.email39@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 39,
                            UserName = "Admin 39"
                        },
                        new
                        {
                            Id = 40,
                            CompanyId = 40,
                            Email = "admin.email40@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 40,
                            UserName = "Admin 40"
                        },
                        new
                        {
                            Id = 41,
                            CompanyId = 41,
                            Email = "admin.email41@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 41,
                            UserName = "Admin 41"
                        },
                        new
                        {
                            Id = 42,
                            CompanyId = 42,
                            Email = "admin.email42@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 42,
                            UserName = "Admin 42"
                        },
                        new
                        {
                            Id = 43,
                            CompanyId = 43,
                            Email = "admin.email43@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 43,
                            UserName = "Admin 43"
                        },
                        new
                        {
                            Id = 44,
                            CompanyId = 44,
                            Email = "admin.email44@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 44,
                            UserName = "Admin 44"
                        },
                        new
                        {
                            Id = 45,
                            CompanyId = 45,
                            Email = "admin.email45@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 45,
                            UserName = "Admin 45"
                        },
                        new
                        {
                            Id = 46,
                            CompanyId = 46,
                            Email = "admin.email46@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 46,
                            UserName = "Admin 46"
                        },
                        new
                        {
                            Id = 47,
                            CompanyId = 47,
                            Email = "admin.email47@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 47,
                            UserName = "Admin 47"
                        },
                        new
                        {
                            Id = 48,
                            CompanyId = 48,
                            Email = "admin.email48@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 48,
                            UserName = "Admin 48"
                        },
                        new
                        {
                            Id = 49,
                            CompanyId = 49,
                            Email = "admin.email49@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 49,
                            UserName = "Admin 49"
                        },
                        new
                        {
                            Id = 50,
                            CompanyId = 50,
                            Email = "admin.email50@email.com",
                            Password = "admin",
                            RoleId = 1,
                            UserInformationId = 50,
                            UserName = "Admin 50"
                        },
                        new
                        {
                            Id = 51,
                            CompanyId = 51,
                            Email = "user.email51@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 51,
                            UserName = "User 51"
                        },
                        new
                        {
                            Id = 52,
                            CompanyId = 52,
                            Email = "user.email52@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 52,
                            UserName = "User 52"
                        },
                        new
                        {
                            Id = 53,
                            CompanyId = 53,
                            Email = "user.email53@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 53,
                            UserName = "User 53"
                        },
                        new
                        {
                            Id = 54,
                            CompanyId = 54,
                            Email = "user.email54@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 54,
                            UserName = "User 54"
                        },
                        new
                        {
                            Id = 55,
                            CompanyId = 55,
                            Email = "user.email55@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 55,
                            UserName = "User 55"
                        },
                        new
                        {
                            Id = 56,
                            CompanyId = 56,
                            Email = "user.email56@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 56,
                            UserName = "User 56"
                        },
                        new
                        {
                            Id = 57,
                            CompanyId = 57,
                            Email = "user.email57@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 57,
                            UserName = "User 57"
                        },
                        new
                        {
                            Id = 58,
                            CompanyId = 58,
                            Email = "user.email58@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 58,
                            UserName = "User 58"
                        },
                        new
                        {
                            Id = 59,
                            CompanyId = 59,
                            Email = "user.email59@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 59,
                            UserName = "User 59"
                        },
                        new
                        {
                            Id = 60,
                            CompanyId = 60,
                            Email = "user.email60@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 60,
                            UserName = "User 60"
                        },
                        new
                        {
                            Id = 61,
                            CompanyId = 61,
                            Email = "user.email61@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 61,
                            UserName = "User 61"
                        },
                        new
                        {
                            Id = 62,
                            CompanyId = 62,
                            Email = "user.email62@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 62,
                            UserName = "User 62"
                        },
                        new
                        {
                            Id = 63,
                            CompanyId = 63,
                            Email = "user.email63@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 63,
                            UserName = "User 63"
                        },
                        new
                        {
                            Id = 64,
                            CompanyId = 64,
                            Email = "user.email64@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 64,
                            UserName = "User 64"
                        },
                        new
                        {
                            Id = 65,
                            CompanyId = 65,
                            Email = "user.email65@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 65,
                            UserName = "User 65"
                        },
                        new
                        {
                            Id = 66,
                            CompanyId = 66,
                            Email = "user.email66@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 66,
                            UserName = "User 66"
                        },
                        new
                        {
                            Id = 67,
                            CompanyId = 67,
                            Email = "user.email67@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 67,
                            UserName = "User 67"
                        },
                        new
                        {
                            Id = 68,
                            CompanyId = 68,
                            Email = "user.email68@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 68,
                            UserName = "User 68"
                        },
                        new
                        {
                            Id = 69,
                            CompanyId = 69,
                            Email = "user.email69@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 69,
                            UserName = "User 69"
                        },
                        new
                        {
                            Id = 70,
                            CompanyId = 70,
                            Email = "user.email70@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 70,
                            UserName = "User 70"
                        },
                        new
                        {
                            Id = 71,
                            CompanyId = 71,
                            Email = "user.email71@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 71,
                            UserName = "User 71"
                        },
                        new
                        {
                            Id = 72,
                            CompanyId = 72,
                            Email = "user.email72@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 72,
                            UserName = "User 72"
                        },
                        new
                        {
                            Id = 73,
                            CompanyId = 73,
                            Email = "user.email73@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 73,
                            UserName = "User 73"
                        },
                        new
                        {
                            Id = 74,
                            CompanyId = 74,
                            Email = "user.email74@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 74,
                            UserName = "User 74"
                        },
                        new
                        {
                            Id = 75,
                            CompanyId = 75,
                            Email = "user.email75@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 75,
                            UserName = "User 75"
                        },
                        new
                        {
                            Id = 76,
                            CompanyId = 76,
                            Email = "user.email76@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 76,
                            UserName = "User 76"
                        },
                        new
                        {
                            Id = 77,
                            CompanyId = 77,
                            Email = "user.email77@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 77,
                            UserName = "User 77"
                        },
                        new
                        {
                            Id = 78,
                            CompanyId = 78,
                            Email = "user.email78@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 78,
                            UserName = "User 78"
                        },
                        new
                        {
                            Id = 79,
                            CompanyId = 79,
                            Email = "user.email79@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 79,
                            UserName = "User 79"
                        },
                        new
                        {
                            Id = 80,
                            CompanyId = 80,
                            Email = "user.email80@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 80,
                            UserName = "User 80"
                        },
                        new
                        {
                            Id = 81,
                            CompanyId = 81,
                            Email = "user.email81@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 81,
                            UserName = "User 81"
                        },
                        new
                        {
                            Id = 82,
                            CompanyId = 82,
                            Email = "user.email82@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 82,
                            UserName = "User 82"
                        },
                        new
                        {
                            Id = 83,
                            CompanyId = 83,
                            Email = "user.email83@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 83,
                            UserName = "User 83"
                        },
                        new
                        {
                            Id = 84,
                            CompanyId = 84,
                            Email = "user.email84@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 84,
                            UserName = "User 84"
                        },
                        new
                        {
                            Id = 85,
                            CompanyId = 85,
                            Email = "user.email85@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 85,
                            UserName = "User 85"
                        },
                        new
                        {
                            Id = 86,
                            CompanyId = 86,
                            Email = "user.email86@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 86,
                            UserName = "User 86"
                        },
                        new
                        {
                            Id = 87,
                            CompanyId = 87,
                            Email = "user.email87@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 87,
                            UserName = "User 87"
                        },
                        new
                        {
                            Id = 88,
                            CompanyId = 88,
                            Email = "user.email88@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 88,
                            UserName = "User 88"
                        },
                        new
                        {
                            Id = 89,
                            CompanyId = 89,
                            Email = "user.email89@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 89,
                            UserName = "User 89"
                        },
                        new
                        {
                            Id = 90,
                            CompanyId = 90,
                            Email = "user.email90@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 90,
                            UserName = "User 90"
                        },
                        new
                        {
                            Id = 91,
                            CompanyId = 91,
                            Email = "user.email91@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 91,
                            UserName = "User 91"
                        },
                        new
                        {
                            Id = 92,
                            CompanyId = 92,
                            Email = "user.email92@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 92,
                            UserName = "User 92"
                        },
                        new
                        {
                            Id = 93,
                            CompanyId = 93,
                            Email = "user.email93@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 93,
                            UserName = "User 93"
                        },
                        new
                        {
                            Id = 94,
                            CompanyId = 94,
                            Email = "user.email94@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 94,
                            UserName = "User 94"
                        },
                        new
                        {
                            Id = 95,
                            CompanyId = 95,
                            Email = "user.email95@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 95,
                            UserName = "User 95"
                        },
                        new
                        {
                            Id = 96,
                            CompanyId = 96,
                            Email = "user.email96@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 96,
                            UserName = "User 96"
                        },
                        new
                        {
                            Id = 97,
                            CompanyId = 97,
                            Email = "user.email97@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 97,
                            UserName = "User 97"
                        },
                        new
                        {
                            Id = 98,
                            CompanyId = 98,
                            Email = "user.email98@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 98,
                            UserName = "User 98"
                        },
                        new
                        {
                            Id = 99,
                            CompanyId = 99,
                            Email = "user.email99@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 99,
                            UserName = "User 99"
                        },
                        new
                        {
                            Id = 100,
                            CompanyId = 100,
                            Email = "user.email100@email.com",
                            Password = "password",
                            RoleId = 2,
                            UserInformationId = 100,
                            UserName = "User 100"
                        });
                });

            modelBuilder.Entity("FHussien_DatabaseSolution.Models.UserInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 1",
                            LastName = "Last Name 1"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 2",
                            LastName = "Last Name 2"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 3",
                            LastName = "Last Name 3"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 4",
                            LastName = "Last Name 4"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 5",
                            LastName = "Last Name 5"
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 6",
                            LastName = "Last Name 6"
                        },
                        new
                        {
                            Id = 7,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 7",
                            LastName = "Last Name 7"
                        },
                        new
                        {
                            Id = 8,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 8",
                            LastName = "Last Name 8"
                        },
                        new
                        {
                            Id = 9,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 9",
                            LastName = "Last Name 9"
                        },
                        new
                        {
                            Id = 10,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 10",
                            LastName = "Last Name 10"
                        },
                        new
                        {
                            Id = 11,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 11",
                            LastName = "Last Name 11"
                        },
                        new
                        {
                            Id = 12,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 12",
                            LastName = "Last Name 12"
                        },
                        new
                        {
                            Id = 13,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 13",
                            LastName = "Last Name 13"
                        },
                        new
                        {
                            Id = 14,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 14",
                            LastName = "Last Name 14"
                        },
                        new
                        {
                            Id = 15,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 15",
                            LastName = "Last Name 15"
                        },
                        new
                        {
                            Id = 16,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 16",
                            LastName = "Last Name 16"
                        },
                        new
                        {
                            Id = 17,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 17",
                            LastName = "Last Name 17"
                        },
                        new
                        {
                            Id = 18,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 18",
                            LastName = "Last Name 18"
                        },
                        new
                        {
                            Id = 19,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 19",
                            LastName = "Last Name 19"
                        },
                        new
                        {
                            Id = 20,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 20",
                            LastName = "Last Name 20"
                        },
                        new
                        {
                            Id = 21,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 21",
                            LastName = "Last Name 21"
                        },
                        new
                        {
                            Id = 22,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 22",
                            LastName = "Last Name 22"
                        },
                        new
                        {
                            Id = 23,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 23",
                            LastName = "Last Name 23"
                        },
                        new
                        {
                            Id = 24,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 24",
                            LastName = "Last Name 24"
                        },
                        new
                        {
                            Id = 25,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 25",
                            LastName = "Last Name 25"
                        },
                        new
                        {
                            Id = 26,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 26",
                            LastName = "Last Name 26"
                        },
                        new
                        {
                            Id = 27,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 27",
                            LastName = "Last Name 27"
                        },
                        new
                        {
                            Id = 28,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 28",
                            LastName = "Last Name 28"
                        },
                        new
                        {
                            Id = 29,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 29",
                            LastName = "Last Name 29"
                        },
                        new
                        {
                            Id = 30,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 30",
                            LastName = "Last Name 30"
                        },
                        new
                        {
                            Id = 31,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 31",
                            LastName = "Last Name 31"
                        },
                        new
                        {
                            Id = 32,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 32",
                            LastName = "Last Name 32"
                        },
                        new
                        {
                            Id = 33,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 33",
                            LastName = "Last Name 33"
                        },
                        new
                        {
                            Id = 34,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 34",
                            LastName = "Last Name 34"
                        },
                        new
                        {
                            Id = 35,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 35",
                            LastName = "Last Name 35"
                        },
                        new
                        {
                            Id = 36,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 36",
                            LastName = "Last Name 36"
                        },
                        new
                        {
                            Id = 37,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 37",
                            LastName = "Last Name 37"
                        },
                        new
                        {
                            Id = 38,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 38",
                            LastName = "Last Name 38"
                        },
                        new
                        {
                            Id = 39,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 39",
                            LastName = "Last Name 39"
                        },
                        new
                        {
                            Id = 40,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 40",
                            LastName = "Last Name 40"
                        },
                        new
                        {
                            Id = 41,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 41",
                            LastName = "Last Name 41"
                        },
                        new
                        {
                            Id = 42,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 42",
                            LastName = "Last Name 42"
                        },
                        new
                        {
                            Id = 43,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 43",
                            LastName = "Last Name 43"
                        },
                        new
                        {
                            Id = 44,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 44",
                            LastName = "Last Name 44"
                        },
                        new
                        {
                            Id = 45,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 45",
                            LastName = "Last Name 45"
                        },
                        new
                        {
                            Id = 46,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 46",
                            LastName = "Last Name 46"
                        },
                        new
                        {
                            Id = 47,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 47",
                            LastName = "Last Name 47"
                        },
                        new
                        {
                            Id = 48,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 48",
                            LastName = "Last Name 48"
                        },
                        new
                        {
                            Id = 49,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 49",
                            LastName = "Last Name 49"
                        },
                        new
                        {
                            Id = 50,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 50",
                            LastName = "Last Name 50"
                        },
                        new
                        {
                            Id = 51,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 51",
                            LastName = "Last Name 51"
                        },
                        new
                        {
                            Id = 52,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 52",
                            LastName = "Last Name 52"
                        },
                        new
                        {
                            Id = 53,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 53",
                            LastName = "Last Name 53"
                        },
                        new
                        {
                            Id = 54,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 54",
                            LastName = "Last Name 54"
                        },
                        new
                        {
                            Id = 55,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 55",
                            LastName = "Last Name 55"
                        },
                        new
                        {
                            Id = 56,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 56",
                            LastName = "Last Name 56"
                        },
                        new
                        {
                            Id = 57,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 57",
                            LastName = "Last Name 57"
                        },
                        new
                        {
                            Id = 58,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 58",
                            LastName = "Last Name 58"
                        },
                        new
                        {
                            Id = 59,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 59",
                            LastName = "Last Name 59"
                        },
                        new
                        {
                            Id = 60,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 60",
                            LastName = "Last Name 60"
                        },
                        new
                        {
                            Id = 61,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 61",
                            LastName = "Last Name 61"
                        },
                        new
                        {
                            Id = 62,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 62",
                            LastName = "Last Name 62"
                        },
                        new
                        {
                            Id = 63,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 63",
                            LastName = "Last Name 63"
                        },
                        new
                        {
                            Id = 64,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 64",
                            LastName = "Last Name 64"
                        },
                        new
                        {
                            Id = 65,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 65",
                            LastName = "Last Name 65"
                        },
                        new
                        {
                            Id = 66,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 66",
                            LastName = "Last Name 66"
                        },
                        new
                        {
                            Id = 67,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 67",
                            LastName = "Last Name 67"
                        },
                        new
                        {
                            Id = 68,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 68",
                            LastName = "Last Name 68"
                        },
                        new
                        {
                            Id = 69,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 69",
                            LastName = "Last Name 69"
                        },
                        new
                        {
                            Id = 70,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 70",
                            LastName = "Last Name 70"
                        },
                        new
                        {
                            Id = 71,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 71",
                            LastName = "Last Name 71"
                        },
                        new
                        {
                            Id = 72,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 72",
                            LastName = "Last Name 72"
                        },
                        new
                        {
                            Id = 73,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 73",
                            LastName = "Last Name 73"
                        },
                        new
                        {
                            Id = 74,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 74",
                            LastName = "Last Name 74"
                        },
                        new
                        {
                            Id = 75,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 75",
                            LastName = "Last Name 75"
                        },
                        new
                        {
                            Id = 76,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 76",
                            LastName = "Last Name 76"
                        },
                        new
                        {
                            Id = 77,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 77",
                            LastName = "Last Name 77"
                        },
                        new
                        {
                            Id = 78,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 78",
                            LastName = "Last Name 78"
                        },
                        new
                        {
                            Id = 79,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 79",
                            LastName = "Last Name 79"
                        },
                        new
                        {
                            Id = 80,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 80",
                            LastName = "Last Name 80"
                        },
                        new
                        {
                            Id = 81,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 81",
                            LastName = "Last Name 81"
                        },
                        new
                        {
                            Id = 82,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 82",
                            LastName = "Last Name 82"
                        },
                        new
                        {
                            Id = 83,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 83",
                            LastName = "Last Name 83"
                        },
                        new
                        {
                            Id = 84,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 84",
                            LastName = "Last Name 84"
                        },
                        new
                        {
                            Id = 85,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 85",
                            LastName = "Last Name 85"
                        },
                        new
                        {
                            Id = 86,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 86",
                            LastName = "Last Name 86"
                        },
                        new
                        {
                            Id = 87,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 87",
                            LastName = "Last Name 87"
                        },
                        new
                        {
                            Id = 88,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 88",
                            LastName = "Last Name 88"
                        },
                        new
                        {
                            Id = 89,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 89",
                            LastName = "Last Name 89"
                        },
                        new
                        {
                            Id = 90,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 90",
                            LastName = "Last Name 90"
                        },
                        new
                        {
                            Id = 91,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 91",
                            LastName = "Last Name 91"
                        },
                        new
                        {
                            Id = 92,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 92",
                            LastName = "Last Name 92"
                        },
                        new
                        {
                            Id = 93,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 93",
                            LastName = "Last Name 93"
                        },
                        new
                        {
                            Id = 94,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 94",
                            LastName = "Last Name 94"
                        },
                        new
                        {
                            Id = 95,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 95",
                            LastName = "Last Name 95"
                        },
                        new
                        {
                            Id = 96,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 96",
                            LastName = "Last Name 96"
                        },
                        new
                        {
                            Id = 97,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 97",
                            LastName = "Last Name 97"
                        },
                        new
                        {
                            Id = 98,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 98",
                            LastName = "Last Name 98"
                        },
                        new
                        {
                            Id = 99,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 99",
                            LastName = "Last Name 99"
                        },
                        new
                        {
                            Id = 100,
                            Birthdate = new DateOnly(1995, 5, 9),
                            FirstName = "First Name 100",
                            LastName = "Last Name 100"
                        });
                });

            modelBuilder.Entity("FHussien_DatabaseSolution.Models.User", b =>
                {
                    b.HasOne("FHussien_DatabaseSolution.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FHussien_DatabaseSolution.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FHussien_DatabaseSolution.Models.UserInformation", "UserInformation")
                        .WithMany()
                        .HasForeignKey("UserInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("UserInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
